#!/usr/bin/env python3
"""Generate cases.jsonl from the input sets, with the ground truth re-verified.

Every negative case is asserted absent from the corpus before it is emitted: a
"no relevant memory exists" label that is actually false would silently reward a
retriever that returns the right row. Refuse to emit rather than emit a lie.

    python3 build_cases.py            # -> cases.jsonl
    python3 build_cases.py --check    # verify cases.jsonl matches its inputs

Splits follow the eval contract: `dev` -> train (used while developing the
grader), the two held-out sets -> test (read once, at the end).
"""

import argparse
import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
INPUTS = HERE / "inputs"
CORPUS = HERE / "corpus.jsonl"
CASES = HERE / "cases.jsonl"

SPLIT_OF = {
    "eval_dev.jsonl": "train",
    "eval_heldout_a.jsonl": "test",
    "eval_heldout_b.jsonl": "test",
}


def read_jsonl(path):
    rows = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            rows.append(json.loads(line))
    return rows


def corpus_blob():
    return " ".join(r["content"].lower() for r in read_jsonl(CORPUS))


def build():
    blob = corpus_blob()
    cases = []

    for name, split in SPLIT_OF.items():
        for i, item in enumerate(read_jsonl(INPUTS / name), start=1):
            stem = name.replace("eval_", "").replace(".jsonl", "")
            category = item.get("category", "uncategorised")
            cases.append({
                "id": f"{stem}_{i:02d}",
                "prompt": item["query"],
                "tags": [category, "positive"],
                "split": split,
                "expect": "hit",
                "relevant": item["relevant"],
                "meta": {"source": name, "origin": "pre-pull harness (.auto/eval_*.jsonl)"},
            })

    for item in read_jsonl(INPUTS / "negatives.jsonl"):
        token = item["probe_token"].lower()
        if token in blob:
            sys.exit(
                f"refusing to emit {item['id']}: probe token {token!r} appears in the "
                "corpus, so this is not a negative case"
            )
        cases.append({
            "id": item["id"],
            "prompt": item["query"],
            "tags": ["negative", "negative"],
            # Negatives live in BOTH splits on purpose: the held-out ones are the
            # honest final specificity number, the train ones are the guardrail a
            # hillclimb can actually see. With every negative held out, a round
            # optimising recall would be blind to over-retrieval until the end.
            "split": item.get("split", "test"),
            "expect": "empty",
            "relevant": [],
            "meta": {
                "source": "inputs/negatives.jsonl",
                "probe_token": token,
                "origin": "authored for this eval; absence verified against corpus.jsonl",
            },
        })

    # every positive label must actually occur in some corpus row, or the case
    # is unanswerable and would count against the retriever forever
    for case in cases:
        if case["expect"] != "hit":
            continue
        if not any(any(rel.lower() in blob for rel in case["relevant"]) for _ in (0,)):
            sys.exit(f"refusing to emit {case['id']}: no relevant text found in corpus")
    return cases


def render_inputs_md(cases):
    """Step 1's sign-off artifact: every input, in full.

    Fences are longer than any backtick run in the case text, so a case can never
    close its own fence.
    """
    lines = [
        "# Input set — recall-quality",
        "",
        f"{len(cases)} cases. Generated by `build_cases.py --inputs-md` from "
        "`inputs/*.jsonl` and `corpus.jsonl`; do not edit by hand.",
        "",
        "Every case is one recall query against a fixed 177-memory corpus. The",
        "`expect` column is what a correct retriever returns; the `expected text`",
        "column is the verbatim span from the corpus that answers it (empty for",
        "negatives, where nothing should come back at all).",
        "",
        "| id | split | category | expect | expected text |",
        "|---|---|---|---|---|",
    ]
    for c in cases:
        expect = ", ".join(f"`{t}`" for t in c["relevant"]) or "_(nothing)_"
        lines.append(f"| `{c['id']}` | {c['split']} | {c['tags'][0]} | "
                     f"{c['expect']} | {expect} |")
    for c in cases:
        text = c["prompt"]
        fence = "`" * max(3, max((len(r) for r in text.split("`")), default=0) + 1)
        lines += ["", f"## `{c['id']}`", "",
                  f"- split: {c['split']}  ·  tags: {', '.join(c['tags'])}  ·  "
                  f"expect: **{c['expect']}**",
                  f"- expected text: {', '.join(c['relevant']) or '_(nothing)_'}",
                  "", f"{fence}text", text, fence]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero if cases.jsonl is stale")
    ap.add_argument("--inputs-md", action="store_true",
                    help="also regenerate inputs.md, the review artifact")
    args = ap.parse_args()

    cases = build()
    rendered = "".join(json.dumps(c, sort_keys=True) + "\n" for c in cases)

    if args.check and not args.inputs_md:
        current = CASES.read_text() if CASES.exists() else ""
        if current != rendered:
            print("cases.jsonl is stale — rerun build_cases.py", file=sys.stderr)
            return 1
        print(f"cases.jsonl matches its inputs ({len(cases)} cases)")
        return 0

    CASES.write_text(rendered)
    n_pos = sum(1 for c in cases if c["expect"] == "hit")
    by_split = {}
    for c in cases:
        by_split.setdefault(c["split"], []).append(c["id"])
    digest = hashlib.sha256(rendered.encode()).hexdigest()[:12]
    print(f"wrote {len(cases)} cases -> {CASES}  ({n_pos} positive, {len(cases) - n_pos} negative)")
    for split, ids in sorted(by_split.items()):
        print(f"  {split:5s} {len(ids):3d}  {ids[0]}..{ids[-1]}")
    print(f"  cases sha256[:12] = {digest}")
    # the report builder reads train_ids/test_ids from _state.json to group rows
    # by split; without them every row renders as split "all".
    state_path = HERE / "_state.json"
    state = json.loads(state_path.read_text()) if state_path.exists() else {}
    for split in ("train", "test"):
        state[f"{split}_ids"] = [c["id"] for c in cases if c["split"] == split]
    state.setdefault("reps", 2)
    state.setdefault("current_round", 0)
    state_path.write_text(json.dumps(state, indent=2) + "\n")
    print(f"updated {state_path} (train_ids, test_ids, reps, current_round)")
    if args.inputs_md:
        (HERE / "inputs.md").write_text(render_inputs_md(cases))
        print(f"wrote {HERE / 'inputs.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())